### ISSUE TITLE
EVERY RELEASE HAS THE WRONG JAR DISTRUBUTED 1.16 HAS BEEN FIXED BUT FUTURE ME FIX THIS WHEN YOU WAKE UP ALSO DON'T WORK WHILE SLEEP DEPRIVED!

### ISSUE THREAD

**Issue by CrimsonDawn45** [CrimsonDawn45/Fabric-Shield-Lib#1]

**Comment by Nathan22211** [comment]
and on top of that, the lib isn't deployed. it only does it locally

**Comment by CrimsonDawn45** [comment]
I was using jitpack to distribute it there is a example mod repo that shows you how to use it
https://github.com/CrimsonDawn45/Fabric-Shield-Lib-Example-Mod

**Comment by CrimsonDawn45** [comment]
Also it might be a few minutes I had to redo all the releases so jitpack has to rebuild all of them
