### ISSUE TITLE
"isShield ran!" message is constantly spammed when the vanilla shield is out.

### ISSUE THREAD

**Issue by ggtylerr** [CrimsonDawn45/Fabric-Shield-Lib#10]
Title. This seems to not affect custom shields, only the vanilla one.

**Comment by CrimsonDawn45** [comment]
Yeah, sorry I haven't had time to work on the code but that is just a bit of test code that is still there somehow.

**Comment by ggtylerr** [comment]
Ah, ok. Should I make a quick PR removing it?

**Comment by CrimsonDawn45** [comment]
If you could that would be great.
