### ISSUE TITLE
Add Config for Shield Disablement Using c:shields

### ISSUE THREAD

**Issue by CringeStar** [CrimsonDawn45/Fabric-Shield-Lib#103]
As @Luligabi1 suggested, we can use the upcoming common tag for shields, `c:shields`, to implement a config in ModMenu for people to toggle between:

1. Disabling a shield disables **only that type of shield** in the inventory and nearby chests to disable for that person (how vanilla shields work)
2. Disabling a shield disables **all other shields** in the inventory and nearby chests to disable for that person (how vanilla shields work)

We do have to wait until the common tag is added to the Fabric API to do so, so for now it is just a reminder/ a place to brainstorm this idea.
Link to track addition of command tag to Fabric API: https://github.com/FabricMC/fabric/pull/2727

**Comment by CrimsonDawn45** [comment]
Well I mean disabling that specific shield would also disable copies of that shield in chests she disabling system goes by the type of item, but yeah I'll add a config option for that.

**Comment by CringeStar** [comment]
I should reword setting one:
 
1. Disabling a shield disables only that type of shield **in the inventory and nearby chests to disable for that person (how vanilla shields work)**

**Comment by CringeStar** [comment]
This update to the FabricAPI was marked as "Likely candidate for future releases", so I think we may be able to implement this feature in the near future, and probably into 1.6.2.

**Comment by CringeStar** [comment]
The common shield tag is now in the newest FabricAPI release, 0.69.0+1.19.3, so we can add this feature now. I'll do it.

**Comment by CringeStar** [comment]
added in #112
