### ISSUE TITLE
Adding a Fabric Shield to an armor stand puts it in wrong slot

### ISSUE THREAD

**Issue by CrimsonDawn45** [CrimsonDawn45/Fabric-Shield-Lib#126]
Instead of the item being added to the MainHand slot shields should be added to the offhand slot for vanilla parity.

**Comment by CringeStar** [comment]
maybe we could do this by mixing into the armor stand class?

**Comment by CrimsonDawn45** [comment]
Yeah that might be the best way to do this. I think there is some kind of method for items where you can define what slot it goes into?

**Comment by CrimsonDawn45** [comment]
There is a method in living entity where it grabs the preferred slot for a given item type
