### ISSUE TITLE
Shields not taking damage unless hit by axe?

### ISSUE THREAD

**Issue by CrimsonDawn45** [CrimsonDawn45/Fabric-Shield-Lib#17]
Everything works in singleplayer but somehow the server is not properly handling/sending the status of the shield back to the client.

**Comment by CrimsonDawn45** [comment]
for some reason, this bug doesn't happen if the player gets hit by an axe? I think it has something to do with the amount having to be above a certain threshold in order for it to be counted as blockedDamage in the mixin? I need to check the vanilla classes to see what is different.

**Comment by CrimsonDawn45** [comment]
Nevermind custom shields don't take damage at all. And vanilla shields only take damage if they are hit with an Axe? Also if a custom shield is hit with an axe it does disable it but it also disables the vanilla shield?

**Comment by CrimsonDawn45** [comment]
And all of this only happens if the player is connected to a multiplayer server with ShieldLib installed???

**Comment by CrimsonDawn45** [comment]
Moved the stuff about custom shields also disabling the vanilla one but not the other way around to a separate issue #18

**Comment by CrimsonDawn45** [comment]
1.3.5's version of 1.16.5 is even worse because I was messing around with the Inject point and made the mixin not run at all 😢

**Comment by CringeStar** [comment]
Should close btw

**Comment by CrimsonDawn45** [comment]
Fixed in 1.4.0
