### ISSUE TITLE
I can't add this in my workspace

### ISSUE THREAD

**Issue by rechalow** [CrimsonDawn45/Fabric-Shield-Lib#26]
see title
I can use gradle in my workspace so I cant add it.
this is my crash report ,I would appreciate it if it is useful!
[crash.txt](https://github.com/CrimsonDawn45/Fabric-Shield-Lib/files/6046291/crash.txt)

**Comment by CrimsonDawn45** [comment]
It says that something interrupted your connection to where it downloads the files from. Weird.
