### ISSUE TITLE
Have Fabric Shield implement an interface so that the features can be implemented via a mixin

### ISSUE THREAD

**Issue by OroArmor** [CrimsonDawn45/Fabric-Shield-Lib#27]
basically, i have to add these features via mixin because i am writing a forge and fabric mod and don't want to use ASM to have things extend classes, but implement interfaces.

~~TBH once i get around to adding shields to FAPI, this wont be an issue anymore~~

**Comment by CrimsonDawn45** [comment]
Yeah, using an interface on an item class instead of just using inheritance to check if it's a shield or not would probably be better.

**Comment by CrimsonDawn45** [comment]
Included in 1.4.0
