### ISSUE TITLE
Split FabricShieldItem class.

### ISSUE THREAD

**Issue by CrimsonDawn45** [CrimsonDawn45/Fabric-Shield-Lib#34]
**Split FabricShieldItem class into two classes.**
- FabricShieldItem(No Banner Support)
- FabricBannerShieldItem(With Banner Support)
- Move `doesSupportBanners` method to `FabricShield` interface.

**Comment by CringeStar** [comment]
Yeah good idea i can work on it when i get home

**Comment by CrimsonDawn45** [comment]
Included in 1.4.1
