### ISSUE TITLE
Ensure next 1.17 release is version agnostic

### ISSUE THREAD

**Issue by StellarWind22** [CrimsonDawn45/Fabric-Shield-Lib#51]
Like 1.15 this will probably work out of the box, but testing should be done to ensure that all behavior is consistent.

**Comment by yesn0t** [comment]
hello @CrimsonDawn45  , releases `1.4.5-1.15`, `1.4.5-1.16`, and `1.4.5-1.17` are missing from modrinth,
is there are way to make them available or would that require a new release ?
thanks x)

**Comment by CrimsonDawn45** [comment]
Oh, sorry about that I forgot to upload those versions to modrinth

**Comment by CrimsonDawn45** [comment]
There they should all be there now.
