### ISSUE TITLE
FabricShieldEnchantments can be enchanted on any item

### ISSUE THREAD

**Issue by dsfhdshdjtsb** [CrimsonDawn45/Fabric-Shield-Lib#57]
The enchantments that are supposed to only show up on shields can show up on any item in the enchantment table(including the reflection enchantment from the dev environment)

**Comment by CringeStar** [comment]
Can confirm, but I cannot figure out why. There is a check for this sort of thing.

```
    @Override
    public boolean isAcceptableItem(ItemStack stack) {
        return stack.getItem() instanceof FabricShield || stack.getItem() instanceof ShieldItem;
    }
```

We have this code but something is wrong. Needs more investigation.

**Comment by CrimsonDawn45** [comment]
What version of minecraft was this in?

**Comment by CringeStar** [comment]
This seems to be a problem with how `isAcceptableItem` works in general

**Comment by CringeStar** [comment]
Here's our problem which someone else is experiencing 
![Uploading Capture+_2021-12-26-17-10-41.png…]()

**Comment by CringeStar** [comment]
![Capture+_2021-12-26-17-10-41](https://user-images.githubusercontent.com/87676346/147424821-8b5f60ee-731c-49d9-91f1-212aa363d78c.png)

**Comment by dsfhdshdjtsb** [comment]
I figured out the problem, but not the solution :)

The Enchantment Table generates valid enchantments for the item by going through every single enchantment and testing if it is valid for the current item(this is in a method in the enchantmentHelper class, forgot name). However, it calls the isAcceptableItem method off of each enchantment's Target(ex: WEAPON, HELMET, BREAKABLE, etc.) not the enchantment itself. That means the isAcceptableItem from the FabricShieldEnchantment is not called, rather the one from its target, BREAKABLE, is called, which makes the enchantment applicable to every breakable item.

I've tried to fix this by using @REDIRECT when the method isAcceptableItem is called, but since it is called off of the enchantment target and not the enchantment, I was still unable to access the overwritten isAcceptableItem. I think heavier mixins could fix this, but it may be a lot of work.

**Comment by dsfhdshdjtsb** [comment]
> ![Capture+_2021-12-26-17-10-41](https://user-images.githubusercontent.com/87676346/147424821-8b5f60ee-731c-49d9-91f1-212aa363d78c.png)
> 
> 

Oh hey thats my post lmao :)

**Comment by CringeStar** [comment]
> I figured out the problem, but not the solution :)
> 
> The Enchantment Table generates valid enchantments for the item by going through every single enchantment and testing if it is valid for the current item(this is in a method in the enchantmentHelper class, forgot name). However, it calls the isAcceptableItem method off of each enchantment's Target(ex: WEAPON, HELMET, BREAKABLE, etc.) not the enchantment itself. That means the isAcceptableItem from the FabricShieldEnchantment is not called, rather the one from its target, BREAKABLE, is called, which makes the enchantment applicable to every breakable item.
> 
> I've tried to fix this by using @reDIrect when the method isAcceptableItem is called, but since it is called off of the enchantment target and not the enchantment, I was still unable to access the overwritten isAcceptableItem. I think heavier mixins could fix this, but it may be a lot of work.

hmm yeah heavy mixins will be needed

**Comment by CringeStar** [comment]
> > ![Capture+_2021-12-26-17-10-41](https://user-images.githubusercontent.com/87676346/147424821-8b5f60ee-731c-49d9-91f1-212aa363d78c.png)
> 
> Oh hey thats my post lmao :)

What a coincidence lol

**Comment by CrimsonDawn45** [comment]
Harvest Sythes has a solution to this.
https://github.com/LordDeatHunter/HarvestScythes/blob/master/src/main/java/wraith/harvest_scythes/enchantment/CustomEnchantmentTargets.java

**Comment by CrimsonDawn45** [comment]
They seem to be using this:
`modImplementation("com.github.Chocohead:Fabric-ASM:v2.3") {
		exclude (group: "net.fabricmc.fabric-api")
	}
	include "com.github.Chocohead:Fabric-ASM:v2.3"`

**Comment by CrimsonDawn45** [comment]
Adding Fabric-ASM seems to break everything else

**Comment by CrimsonDawn45** [comment]
Never mind I was doing it wrong last time. This has been fixed in the latest commit
