### ISSUE TITLE
JitPack build is broken

### ISSUE THREAD

**Issue by RedGrapefruit09** [CrimsonDawn45/Fabric-Shield-Lib#59]
It is currently not possible to get the `1.4.5-1.18` artifact from JitPack.

As a temporary solution, I've built the mod and hosted it on my Maven. [direct link](https://redgrapefruit09.github.io/maven/forked/crimsondawn45/fabricshieldlib/fabricshieldlib/1.4.5-1.18/fabricshieldlib-1.4.5-1.18.jar).

I hope this issue gets resolved as soon as possible.

**Comment by CringeStar** [comment]
This is not an issue with the mod, it is more me forgetting to update the wiki properly,

replace the modImplementation in your build.gradle with this:
`	modImplementation "com.github.CrimsonDawn45:Fabric-Shield-Lib:v${project.fabric_shield_lib_version}"`

**Comment by RedGrapefruit09** [comment]
> This is not an issue with the mod, it is more wrong documentaion
> 
> replace the modImplementation in your build.gradle with this: ` modImplementation "com.github.CrimsonDawn45:Fabric-Shield-Lib:v${project.fabric_shield_lib_version}"`

ok, thx
