### ISSUE TITLE
Mod includes test shield and enchantment

### ISSUE THREAD

**Issue by Draylar** [CrimsonDawn45/Fabric-Shield-Lib#7]
https://github.com/CrimsonDawn45/Fabric-Shield-Lib/blob/ff33251e1104a547807efdbdd3a5595642104a03/src/main/java/me/crimsondawn45/fabricshieldlib/FabricShieldLib.java#L30-L33

Unless I'm missing something or looking at the wrong branch, Fabric Shield Lib is shipping a test shield, test enchantment, and test event in and outside development environments. These calls should be wrapped in a `FabricLoader.getInstance().isDevelopmentEnvironment()` call so they are not registered in production (= outside an IDE, when users play the game).

![image](https://user-images.githubusercontent.com/17728338/92312629-3743c380-ef88-11ea-9f6b-5e587367e2e8.png)

**Comment by Spaceman** [comment]
I considered doing this but I decided against it to mitigate possible client server desync

**Comment by Draylar** [comment]
The issue is dev env vs. production env, not client vs. server. Prod clients do not connect to dev servers.

**Comment by Spaceman** [comment]
I realize that but I was unsure how accurate the detection was between dev and prod environment.
