### ISSUE TITLE
Add tooltip for showing shield cooldown time for axes

### ISSUE THREAD

**Issue by CrimsonDawn45** [CrimsonDawn45/Fabric-Shield-Lib#74]
Shield's should have a tool tip like:

When disabled:
          0.8s Cooldown

**Comment by CrimsonDawn45** [comment]
also this will need to be done in a way that allows us to use .lang files for translations

**Comment by CrimsonDawn45** [comment]
We should also add a config setting to disable the tooltip

**Comment by Jab125** [comment]
you can extend the `FabricShieldItem` and change its tooltip
