### ISSUE TITLE
incompatibility with Medieval Weapons mod

### ISSUE THREAD

**Issue by celophys** [CrimsonDawn45/Fabric-Shield-Lib#77]
When using this mod and medieval weapons, every shield stop working and you take all the damage

**Comment by rikka0w0** [comment]
Can you post the link to the medieval mod here?

The most straightforward way to add a shield is to redirect a function call with Mixin:
https://github.com/rikka0w0/MobZReborn/blob/5b067930d58e0a65ecb28f2b0600eabf06fccb0f/fabric/src/main/java/net/mobz/mixin/PlayerEntityMixin.java

Many mods do this, but it makes these mods mutually incompatible with each other.

**Comment by celophys** [comment]
The link of the mod: https://www.curseforge.com/minecraft/mc-mods/medievalweapons
The issues with fabric shields lib: https://github.com/Globox1997/MedievalWeapons/issues/60

**Comment by celophys** [comment]
The link of the mod: https://www.curseforge.com/minecraft/mc-mods/medievalweapons
The issues with fabric shields lib: https://github.com/Globox1997/MedievalWeapons/issues/60

**Comment by rikka0w0** [comment]
I think something is wrong with this:
https://github.com/Globox1997/MedievalWeapons/blob/cabfaa96cd0b7ae56c7c619320e238d6b31309f6/src/main/java/net/medievalweapons/mixin/PlayerEntityMixin.java#L44-L50

**Comment by CrimsonDawn45** [comment]
Looking between these mods I'm not sure if there is a good way for me to resolve this issue on my end.

**Comment by celophys** [comment]
https://user-images.githubusercontent.com/84269120/152639688-62708f12-16a6-40af-985d-8e6c7278f225.mp4

A video of the issue

**Comment by rikka0w0** [comment]
> Looking between these mods I'm not sure if there is a good way for me to resolve this issue on my end.

You don't need to do anything on your end, I believe it is MedievalWeapons' bug

**Comment by CrimsonDawn45** [comment]
This issue has been resolved on MedievalWeapon's end
