### ISSUE TITLE
ShieldBlockCallback

### ISSUE THREAD

**Issue by TheButterbrotMan** [CrimsonDawn45/Fabric-Shield-Lib#87]
https://bytebin.lucko.me/BXv7OCp1bR

**Comment by CrimsonDawn45** [comment]
Sorry about taking 4 months to answer, I had a lot of things going on irl lol.

Anyway. Was this just you running the mod? Or are you developing a mod using this library? I can't really do anything with this little information.

**Comment by CrimsonDawn45** [comment]
If this issue occurs again, or if you return with more information about what is going on feel free to re-open this issue.
