### ISSUE TITLE
Shields made with this library don't take damage or cooldown. [1.16.3]

### ISSUE THREAD

**Issue by loleq2105** [CrimsonDawn45/Fabric-Shield-Lib#9]
As the title says. This is the case with the example shield that comes with the library, too! Extra Shield for Fabric's shields have the same issue as well. My custom shield as well (I did everything correctly, the shield blocking logic is fine, but durability/cooldown mechanics are bust, like with any other shield made with this library). Note that this issue occurs in the version 1.16.3, I'm uncertain if it occurs in the previous one too, haven't tested. Latest fabric loader/API as of today.

**Comment by Spaceman** [comment]
Unfortunately I do not have time to debug this, i can however review and merge PRs if you would like to fix this issue.

**Comment by CrimsonDawn45** [comment]
I did some digging around and it's strange how the mod was handling this before was literally just invoking the vanilla code for damaging the shield and applying cooldown but the vanilla code is just an empty method now? I will work on this more later, but right now I can't even find where vanilla is handing shields being damaged.

**Comment by CrimsonDawn45** [comment]
I have changed around a bunch of stuff and this is still not fixed I really have no idea what is causing this. This one bug has been the downfall of this entire library. I might try rebuilding this entire mod and if that doesn't work idk.

**Comment by How-Bout-No** [comment]
Don't mean to revive an old issue but just changing the value from TAIL to HEAD in the mixin works just fine, idk why it is set to TAIL since there is no return value in damageShield. It might be a similar issue with the disableShield mixin as well.
