### ISSUE TITLE
Incompatible with Guarding and Harvest Scythes

### ISSUE THREAD

**Issue by Sunconure11** [CrimsonDawn45/Fabric-Shield-Lib#90]
https://github.com/ExDrill/Guarding/issues/2

**Comment by CringeStar** [comment]
@Sunconure11 Does this issue persist on the newest release?

**Comment by ExDrill** [comment]
Guarding should no longer be an issue, as it doesn't rely on Fabric Shield Lib at the moment (in 1.19+ releases)

**Comment by CringeStar** [comment]
Thanks for the updates, I will closs this issue for now.
