### ISSUE TITLE
Model not working

### ISSUE THREAD

**Issue by shadowradience** [CrimsonDawn45/Fabric-Shield-Lib#91]
Following the "Adding a Shield" on the fabric wiki doesn't work. All i've tried to do here is add the basic shield step by step verbatim what's on the wiki, but it seems like the item itself gets registered and the hot bar shield shows up, however its completely invisible when you hold it or try to block with it.

**Comment by CringeStar** [comment]
i have updated the wiki for 1.17-1.18 and in general, can you try again with the new guide and tell me if your issue got fixed?

**Comment by CrimsonDawn45** [comment]
I'll close this issue as it was originally opened more than three months ago & it's not likely the original poster will update us on whether this was resolved.
