### ISSUE TITLE
1.18.2 weird error message

### ISSUE THREAD

**Issue by ethan629** [CrimsonDawn45/Fabric-Shield-Lib#93]
I followed everything and added 
`maven { url = "https://maven.shedaniel.me/" }
maven { url = "https://maven.terraformersmc.com/" }`

but i got the error message 
`java.lang.RuntimeException: Invalid module: private static transient int[] me.shedaniel.autoconfig.example.ExampleConfig.__$lineHits$__
`

any help?

**Comment by CrimsonDawn45** [comment]
Duplicate of #83
