### ISSUE TITLE
This project is abandoned

### ISSUE THREAD

**Issue by CrimsonDawn45** [CrimsonDawn45/Fabric-Shield-Lib#98]
I no longer have the time or energy to maintain this project as I don't make much at all from doing this. My life has gotten much more complicated. I might come back I might not everything is very uncertain for me right now. Right now this is only one more thing for me to worry about and I already have too much on my plate.

**Comment by CringeStar** [comment]
Hey, could I also take over the project? I've helped with it enough that I feel I could continue it for the most part. I already sent a dm on discord.

**Comment by CrimsonDawn45** [comment]
I was working on something else then realized I can fix pretty much all the problems by just temporarily removing enchantment support. Vanilla & modded generic enchantments will still work and custom event's for special shields will still work but not shield enchantments that work via the enchantment table.
